### Cadastrar despesa
POST http://localhost:3333
Content-Type: application/json

{
    "descricao" : "Conta de luz",
    "preco" : 120
}

### Listar despesas
GET http://localhost:3333

### Calcular despesas
GET http://localhost:3333/calcular


