### Requisição para a raiz da aplicação
GET http://localhost:3000

### Requisição passando parametros na URL
GET http://localhost:3000/12/arroz

### Requisição passando informação pelo corpo da requisição / Cadastrar produto
POST http://localhost:3000
Content-Type: application/json

{
    "nome" : "Arroz",
    "preco" : 10
}
