### Listar produtos
GET http://localhost:3001

### Requisição passando parametros na URL
GET http://localhost:3001/1

### Cadastrar produto
POST http://localhost:3001
Content-Type: application/json

{
    "nome" : "Bolacha",
    "preco" : 10
}
